Add file to encapsulate python env with conda
Enforcing install of 'numpy' before 'obspy' is collected due to this
compilation error:

$ ~/github/forks/FAST (master) :: pip install -r requirements.txt
Collecting PyWavelets
  Using cached PyWavelets-1.1.1-cp37-cp37m-macosx_10_9_x86_64.whl (4.3 MB)
Collecting obspy
  Using cached obspy-1.2.1.zip (24.7 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/anaconda3/envs/fast/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9y/6kx7fns90pn84gtycx7dyl680000gn/T/pip-install-vx4v_dfj/obspy/setup.py'"'"'; __file__='"'"'/private/var/folders/9y/6kx7fns90pn84gtycx7dyl680000gn/T/pip-install-vx4v_dfj/obspy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/9y/6kx7fns90pn84gtycx7dyl680000gn/T/pip-pip-egg-info-l5fdrf66
         cwd: /private/var/folders/9y/6kx7fns90pn84gtycx7dyl680000gn/T/pip-install-vx4v_dfj/obspy/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/private/var/folders/9y/6kx7fns90pn84gtycx7dyl680000gn/T/pip-install-vx4v_dfj/obspy/setup.py", line 33, in <module>
        import numpy  # @UnusedImport # NOQA
    ModuleNotFoundError: No module named 'numpy'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9y/6kx7fns90pn84gtycx7dyl680000gn/T/pip-install-vx4v_dfj/obspy/setup.py", line 37, in <module>
        raise ImportError(msg)
    ImportError: No module named numpy. Please install numpy first, it is needed before installing ObsPy.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Collecting 'numpy' first via conda-forge allows for requirements to be
installed smoothly with directive in 'environment.yml' file, i.e:

    - pip:
      - -r file:requirements.txt

	new file:   environment.yml
	modified:   requirements.txt